language: generic
sudo: false

env:
    global:
    - BYOND_MAJOR="512"
    - BYOND_MINOR="1454"
    - DM_BUILDFILE="taucetistation.dme"

cache:
  directories:
    - $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}

addons:
  apt:
    packages:
      - libc6-i386
      - libgcc1:i386
      - libstdc++6:i386

before_script:
  - chmod +x ./install-byond.sh 
  - ./install-byond.sh

script:
  - (! grep 'step_[xy]' maps/*.dmm)
  - (! grep -E "(/obj/machinery/door/firedoor).*\1" maps/*.dmm)
  - source $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}/byond/bin/byondsetup
#  - bash dm.sh -M${DM_MAPFILE} ${DM_BUILDFILE}
  - bash dm.sh ${DM_BUILDFILE}
